name: Lint Check CI

on: pull_request


jobs:  
  my_first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps: 
    - run: echo "My first job!!!!!!!!!"
  my_second_job:
    name: My second job
    runs-on: ubuntu-latest
    steps:
    - run: echo "My second job!!!!!!!!!"