name: Lint Check CI

on: pull_request

jobs:  
  my_first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps: 
    - run: echo "My first job!!!!!!!!!"
  my_second_job:
    name: My second job
    runs-on: ubuntu-latest
    steps:
    - run: echo "My second job!!!!!!!!!"
  my_thierd_job:
    name: My third job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: go version
    - uses: actions/setup-go@v3
      with:
       go-version: 1.19
    - run: go version